language: ruby
os: linux
dist: xenial

rvm:
  - 2.6.5
  - 2.5.7
  - 2.4.9

services:
  - postgresql

env:
  - REDMINE_VER=4.0-stable
  - REDMINE_VER=master

before_install:
  - export DB=postgresql
  - export PLUGIN_NAME=redmine_codimd
  - export REDMINE_GIT_REPO=git://github.com/redmine/redmine.git
  - export REDMINE_PATH=$HOME/redmine
  - export BUNDLE_GEMFILE=$REDMINE_PATH/Gemfile
  - export RAILS_ENV=test
  - git clone $REDMINE_GIT_REPO $REDMINE_PATH
  - cd $REDMINE_PATH
  - if [[ "$REDMINE_VER" != "master" ]]; then git checkout -b $REDMINE_VER origin/$REDMINE_VER; fi
  - cp $TRAVIS_BUILD_DIR/test/support/Gemfile.local $REDMINE_PATH
  - ln -s $TRAVIS_BUILD_DIR $REDMINE_PATH/plugins/$PLUGIN_NAME
  - git clone git://github.com/alphanodes/additionals.git $REDMINE_PATH/plugins/additionals
  - cp $TRAVIS_BUILD_DIR/test/support/additional_environment.rb $REDMINE_PATH/config/
  - cp $TRAVIS_BUILD_DIR/test/support/database-$DB-travis.yml $REDMINE_PATH/config/database.yml

before_script:
  - bundle exec rake db:create:all
  - psql codimd_travis < $TRAVIS_BUILD_DIR/test/support/codimd.sql
  - bundle exec rake db:migrate redmine:plugins:migrate

script:
  - if [[ "$REDMINE_VER" != "master" ]]; then rubocop plugins/$PLUGIN_NAME; fi
  - bundle exec rake redmine:plugins:test NAME=$PLUGIN_NAME RUBYOPT="-W0"
  - bundle exec rake redmine:plugins:migrate NAME=$PLUGIN_NAME VERSION=0
